### ISSUE TITLE
Fix rust version in the tests to match with kata

### ISSUE THREAD

**Issue by surajssd** [confidential-containers/guest-components#330]
Right now in the GH workflows we use the latest rust version and not one fixed to match / align with the kata. Kata is the downstream project consuming guest components. IMO it makes sense to align on the rust version in all the projects.

**Comment by arronwy** [comment]
Current Kata main/CCv0 use rust toolchain version 1.66:
```
  rust:
    description: "Rust language"
    notes: "'version' is the default minimum version used by this project."
    version: "1.69.0"
    meta:
      description: |
        'newest-version' is the latest version known to work when
        building Kata
      newest-version: "1.69.0"
```

and `image-rs` CI use below matrix:
```
stable-x86_64-unknown-linux-gnu unchanged - rustc 1.72.0 (5680fa18f 2023-08-23)
beta-x86_64-unknown-linux-gnu installed - rustc 1.73.0-beta.1 (680cdf816 2023-08-21)
nightly-x86_64-unknown-linux-gnu unchanged - rustc 1.74.0-nightly (58eefc33a 2023-08-24)
```

To avoid potential break Kata CI, suggest switch use below new matric:
```
1.69.0
stable
nightly
```
any suggestions? @Xynnn007 @fitzthum @sameo
