### ISSUE TITLE
Pull nydus image failed in CoCo with the kata-agent enabled the nydus feature

### ISSUE THREAD

**Issue by ChengyuZhu6** [confidential-containers/guest-components#474]
Cargo.toml in kata-agent:
```
image-rs = { git = "https://github.com/confidential-containers/guest-components", tag = "v0.8.0" ,  features = [ "getresource", "snapshot-overlayfs", "nydus" ], optional = true }
```
pod yaml: 
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-nydus
  annotations:
    io.containerd.cri.runtime-handler: kata-qemu
spec:
  runtimeClassName: kata-qemu
  containers:
  - name: ubuntu-nydus
    image: eci-nydus-registry.cn-hangzhou.cr.aliyuncs.com/test/ubuntu:latest_nydus
    imagePullPolicy: Always
```

```bash
Stack backtrace:
   0: <futures_util::stream::futures_unordered::FuturesUnordered<Fut> as futures_core::stream::Stream>::poll_next
   1: <futures_util::stream::try_stream::try_collect::TryCollect<St,C> as core::future::future::Future>::poll
   2: image_rs::pull::PullClient::async_pull_layers::{{closure}}.30613
   3: image_rs::image::ImageClient::pull_image::{{closure}}.30480
   4: <kata_agent::storage::image_pull_handler::ImagePullHandler as kata_agent::storage::StorageHandler>::create_device::{{closure}}
   5: kata_agent::storage::add_storages::{{closure}}
   6: kata_agent::rpc::AgentService::do_create_container::{{closure}}::{{closure}}
   7: <kata_agent::rpc::AgentService as protocols::agent_ttrpc_async::AgentService>::create_container::{{closure}}
   8: <protocols::agent_ttrpc_async::CreateContainerMethod as ttrpc::asynchronous::utils::MethodHandler>::handler::{{closure}}
   9: ttrpc::asynchronous::server::HandlerContext::handle_msg::{{closure}}
  10: <ttrpc::asynchronous::server::ServerReader as ttrpc::asynchronous::connection::ReaderDelegate>::handle_msg::{{closure}}::{{closure}}
  11: tokio::runtime::task::raw::poll
  12: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  13: tokio::runtime::task::raw::poll
  14: std::sys_common::backtrace::__rust_begin_short_backtrace
  15: core::ops::function::FnOnce::call_once{{vtable.shim}}
  16: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at ./rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/alloc/src/boxed.rs:1993:9
  17: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at ./rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/alloc/src/boxed.rs:1993:9
  18: std::sys::unix::thread::Thread::new::thread_start
             at ./rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/sys/unix/thread.rs:108:17: unknown
```
