### ISSUE TITLE
Image pull issue: failed to handle layer

### ISSUE THREAD

**Issue by enuoCM** [confidential-containers/guest-components#544]
CoCo 0.8.0
A simple test yaml:
```
apiVersion: v1
kind: Pod
metadata:
  name: distroless-12
  annotations:
    io.containerd.cri.runtime-handler: kata-qemu
spec:
  runtimeClassName: kata-qemu
  containers:
  - name: app
    image: gcr.io/distroless/base-debian12:debug
    command:
      - sh
      - -c
      - "sleep 10000"
```

error:
```
Warning  Failed     9s (x2 over 18s)   kubelet            Error: failed to create containerd task: failed to create shim task: failed to handle layer: hasher sha256: channel: send failed SendError { .. }: unknown
```

seems the issue happens on 'image-rs/src/stream.rs#channel_processing'
```
  tx.send(buffer)
            .map_err(|e| anyhow!("channel: send failed {:?}", e))?;
```

BTW, if change the image to 'gcr.io/distroless/base-debian11:debug', then no such issue.
