### ISSUE TITLE
deploy enclave-cc failed

### ISSUE THREAD

**Issue by reclock** [confidential-containers/guest-components#546]
![image](https://github.com/confidential-containers/guest-components/assets/23696606/410140b2-88b7-4d65-97bb-a3f5587fa545)

**Comment by reclock** [comment]
this is my yaml:

```
apiVersion: v1
kind: Pod
metadata:
  name: enclave-cc-pod-test
spec:
  containers:
  - image: docker.io/zjqdocker/hello-sgx-cc-encrypted
    name: hello-world
    workingDir: "/run/rune/boot_instance/"
    env:
    - name: OCCLUM_RELEASE_ENCLAVE
      value: "1"
    command:
    - /run/rune/boot_instance/build/bin/occlum-run
    - /bin/hello_world
  runtimeClassName: enclave-cc
```
