### ISSUE TITLE
Discuss the problem of confidential container pull mirror

### ISSUE THREAD

**Issue by panpingsheng** [confidential-containers/guest-components#601]
The dockerhub network is unstable, causing an unstable pull image from the dockerhub repository in the confidential container virtual machine
1. On the host, you can set a domestic acceleration source, for example
higon@higon:~$ cat /etc/docker/daemon.json
{
"registry-mirrors": ["https://registry.docker-cn.com","https://s3d6l2fh.mirror.aliyuncs.com"]
}
Can confidential container VMS also provide corresponding methods to avoid this problem? 
2. At present, you can set the proxy method to avoid this problem, as follows:
kernel_params = "agent.https_proxy=http://10.61.40.54:7890 agent.no_proxy=.hygon.cn,10... , 172... * agent.enable_signature_verification=false "
However, domestic customers do not necessarily have an external network agent, hoping to provide a similar host-like circumvention scheme

**Comment by Xynnn007** [comment]
This can be resolved by #896 with the following example registry configuration toml

```toml
[[registry]]
prefix = "docker.io"

[[registry.mirror]]
location = "registry.docker-cn.com"

[[registry.mirror]]
location = "s3d6l2fh.mirror.aliyuncs.com"
```

Let me close this one.
